name: Stravaig Configuration Diagnostics
env:
  STRAVAIG_SOLUTION: src/Stravaig.Extensions.Configuration.Diagnostics.sln
  STRAVAIG_TESTS: Stravaig.Extensions.Configuration.Diagnostics.Tests
  STRAVAIG_PROJECT: Stravaig.Extensions.Configuration.Diagnostics
on: 
  push:
    branches: 
      - main
      - "#32-automate-release-tagging"
    paths-ignore:
      - 'README.md'
      - 'Example/**'
      - '.vscode/**'
      - '.gitignore'

  pull_request:
    types: [assigned, opened, synchronize, reopened]
    paths-ignore:
      - 'README.md'
      - 'Example/**'
      - '.vscode/**'
      - '.gitignore'

  workflow_dispatch:
    inputs:
      isPublic:
        description: 'Is Public Release'     
        required: false
        default: "false"
      isPreview:
        description: 'Is Preview Release'
        required: false
        default: "true"

jobs:
  build:
    name: Build, Test, and Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set version number
        shell: pwsh
        run: ./Set-Version.ps1 -IsPublic "${{ github.event.inputs.isPublic }}" -IsPreview "${{ github.event.inputs.isPreview }}"

      - name: Display workflow state
        run: |
          echo "Solution: $STRAVAIG_SOLUTION"
          echo "Project: $STRAVAIG_PROJECT"
          echo "Tests: $STRAVAIG_TESTS"
          echo "Package version: $STRAVAIG_PACKAGE_VERSION"
          echo "Version Suffix: $STRAVAIG_PACKAGE_VERSION_SUFFIX"
          echo "Publish To NuGet: $STRAVAIG_PUBLISH_TO_NUGET"
          
      - uses: actions/setup-dotnet@v1
        name: Setup .NET Core
        with:
          dotnet-version: 3.1.404

      - name: Build Solution
        run: dotnet build $STRAVAIG_SOLUTION --configuration Release
       
      - name: Run Tests
        run: dotnet test src/$STRAVAIG_TESTS/$STRAVAIG_TESTS.csproj --configuration Release
       
      - name: Package Preview Release
        if: ${{ env.STRAVAIG_PACKAGE_VERSION_SUFFIX != '~' }}
        run: dotnet pack ./src/$STRAVAIG_PROJECT/$STRAVAIG_PROJECT.csproj --configuration Release --output ./out --include-symbols --include-source /p:VersionPrefix="$STRAVAIG_PACKAGE_VERSION" --version-suffix "$STRAVAIG_PACKAGE_VERSION_SUFFIX" -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg
       
      - name: Package Stable Release
        if: ${{ env.STRAVAIG_PACKAGE_VERSION_SUFFIX == '~' }}
        run: dotnet pack ./src/$STRAVAIG_PROJECT/$STRAVAIG_PROJECT.csproj --configuration Release --output ./out --include-symbols --include-source /p:VersionPrefix="$STRAVAIG_PACKAGE_VERSION" -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg

      - name: Push package to NuGet
        if: ${{ env.STRAVAIG_PUBLISH_TO_NUGET == 'true' }}
        run: dotnet nuget push ./out/*.nupkg --api-key ${{ secrets.STRAVAIG_NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

      - name: List Contributors
        shell: pwsh
        run: ./list-contributors.ps1
      - name: Archive Contriubutors
        uses: actions/upload-artifact@v2
        with:
          name: release-information
          path: contributors.md